export const data = [
  {
    name: "Day 1",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 2",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 3",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 4",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 5",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 6",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 7",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 8",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 9",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 10",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 11",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 12",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 13",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 14",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 15",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 16",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 17",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 18",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 19",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 20",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 21",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 22",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 23",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 24",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 25",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 26",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 27",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 28",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 29",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
  {
    name: "Day 30",
    uv: getRandomNumber(),
    pv: getRandomNumber(),
    amt: getRandomNumber(),
  },
];

function getRandomNumber() {
  return Math.floor(Math.random() * 50); // Retorna um número aleatório entre 0 e 999
}
